defmodule SecopService.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :confirmed_at, :utc_datetime_usec
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sec_nodes, primary_key: false) do
      add :uuid, :uuid, null: false, primary_key: true
      add :equipment_id, :text, null: false
      add :host, :text, null: false
      add :port, :bigint, null: false
      add :description, :text
      add :firmware, :text
      add :implementor, :text
      add :timeout, :bigint
      add :describe_message, :map
      add :describe_message_raw, :text
      add :custom_properties, :map
      add :check_result, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:sec_nodes, [:equipment_id], name: "equipment_id_index")

    create unique_index(:sec_nodes, [:uuid], name: "sec_nodes_unique_uuid_index")

    create table(:parameters, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :datainfo, :map
      add :readonly, :boolean
      add :description, :text
      add :group, :text
      add :visibility, :text
      add :meaning, :map
      add :checkable, :boolean
      add :custom_properties, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :module_id, :bigint, null: false
    end

    create table(:parameter_values_string, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, :text, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_string_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_string, [:timestamp],
             name: "parameter_values_string_timestamp_index"
           )

    create index(:parameter_values_string, [:parameter_id, :timestamp],
             name: "parameter_values_string_parameter_id_timestamp_index"
           )

    create table(:parameter_values_json, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, :map, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_json_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_json, [:value],
             name: "parameter_values_json_value_index",
             using: "gin"
           )

    create index(:parameter_values_json, [:timestamp],
             name: "parameter_values_json_timestamp_index"
           )

    create index(:parameter_values_json, [:parameter_id, :timestamp],
             name: "parameter_values_json_parameter_id_timestamp_index"
           )

    create table(:parameter_values_int, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, :bigint, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_int_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_int, [:timestamp],
             name: "parameter_values_int_timestamp_index"
           )

    create index(:parameter_values_int, [:parameter_id, :timestamp],
             name: "parameter_values_int_parameter_id_timestamp_index"
           )

    create table(:parameter_values_double, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, :decimal, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_double_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_double, [:timestamp],
             name: "parameter_values_double_timestamp_index"
           )

    create index(:parameter_values_double, [:parameter_id, :timestamp],
             name: "parameter_values_double_parameter_id_timestamp_index"
           )

    create table(:parameter_values_bool, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, :boolean, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_bool_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_bool, [:timestamp],
             name: "parameter_values_bool_timestamp_index"
           )

    create index(:parameter_values_bool, [:parameter_id, :timestamp],
             name: "parameter_values_bool_parameter_id_timestamp_index"
           )

    create table(:parameter_values_array_string, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, {:array, :text}, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_array_string_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_array_string, [:timestamp],
             name: "parameter_values_array_string_timestamp_index"
           )

    create index(:parameter_values_array_string, [:parameter_id, :timestamp],
             name: "parameter_values_array_string_parameter_id_timestamp_index"
           )

    create table(:parameter_values_array_int, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, {:array, :bigint}, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_array_int_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_array_int, [:timestamp],
             name: "parameter_values_array_int_timestamp_index"
           )

    create index(:parameter_values_array_int, [:parameter_id, :timestamp],
             name: "parameter_values_array_int_parameter_id_timestamp_index"
           )

    create table(:parameter_values_array_double, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, {:array, :float}, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_array_double_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_array_double, [:timestamp],
             name: "parameter_values_array_double_timestamp_index"
           )

    create index(:parameter_values_array_double, [:parameter_id, :timestamp],
             name: "parameter_values_array_double_parameter_id_timestamp_index"
           )

    create table(:parameter_values_array_bool, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :value, {:array, :boolean}, null: false
      add :timestamp, :utc_datetime_usec, null: false
      add :qualifiers, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parameter_id,
          references(:parameters,
            column: :id,
            name: "parameter_values_array_bool_parameter_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:parameter_values_array_bool, [:timestamp],
             name: "parameter_values_array_bool_timestamp_index"
           )

    create index(:parameter_values_array_bool, [:parameter_id, :timestamp],
             name: "parameter_values_array_bool_parameter_id_timestamp_index"
           )

    create table(:modules, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:parameters) do
      modify :module_id,
             references(:modules,
               column: :id,
               name: "parameters_module_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:parameters, [:module_id, :name], name: "parameters_module_id_name_index")

    alter table(:modules) do
      add :name, :text, null: false
      add :description, :text
      add :interface_classes, {:array, :text}
      add :highest_interface_class, :text
      add :visibility, :text
      add :group, :text
      add :meaning, :map
      add :implementor, :text
      add :custom_properties, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sec_node_id,
          references(:sec_nodes,
            column: :uuid,
            name: "modules_sec_node_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:modules, [:sec_node_id, :name], name: "modules_sec_node_id_name_index")

    create table(:commands, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :datainfo, :map
      add :custom_properties, :map
      add :argument, :map
      add :result, :map
      add :group, :text
      add :visibility, :text
      add :meaning, :map
      add :checkable, :boolean

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :module_id,
          references(:modules,
            column: :id,
            name: "commands_module_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:commands, [:module_id, :name], name: "commands_module_id_name_index")

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "api_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_index")

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    drop table(:api_keys)

    drop_if_exists unique_index(:commands, [:module_id, :name],
                     name: "commands_module_id_name_index"
                   )

    drop constraint(:commands, "commands_module_id_fkey")

    drop table(:commands)

    drop_if_exists unique_index(:modules, [:sec_node_id, :name],
                     name: "modules_sec_node_id_name_index"
                   )

    drop constraint(:modules, "modules_sec_node_id_fkey")

    alter table(:modules) do
      remove :sec_node_id
      remove :updated_at
      remove :inserted_at
      remove :custom_properties
      remove :implementor
      remove :meaning
      remove :group
      remove :visibility
      remove :highest_interface_class
      remove :interface_classes
      remove :description
      remove :name
    end

    drop_if_exists unique_index(:parameters, [:module_id, :name],
                     name: "parameters_module_id_name_index"
                   )

    drop constraint(:parameters, "parameters_module_id_fkey")

    alter table(:parameters) do
      modify :module_id, :bigint
    end

    drop table(:modules)

    drop constraint(:parameter_values_array_bool, "parameter_values_array_bool_parameter_id_fkey")

    drop_if_exists index(:parameter_values_array_bool, [:parameter_id, :timestamp],
                     name: "parameter_values_array_bool_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_array_bool, [:timestamp],
                     name: "parameter_values_array_bool_timestamp_index"
                   )

    drop table(:parameter_values_array_bool)

    drop constraint(
           :parameter_values_array_double,
           "parameter_values_array_double_parameter_id_fkey"
         )

    drop_if_exists index(:parameter_values_array_double, [:parameter_id, :timestamp],
                     name: "parameter_values_array_double_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_array_double, [:timestamp],
                     name: "parameter_values_array_double_timestamp_index"
                   )

    drop table(:parameter_values_array_double)

    drop constraint(:parameter_values_array_int, "parameter_values_array_int_parameter_id_fkey")

    drop_if_exists index(:parameter_values_array_int, [:parameter_id, :timestamp],
                     name: "parameter_values_array_int_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_array_int, [:timestamp],
                     name: "parameter_values_array_int_timestamp_index"
                   )

    drop table(:parameter_values_array_int)

    drop constraint(
           :parameter_values_array_string,
           "parameter_values_array_string_parameter_id_fkey"
         )

    drop_if_exists index(:parameter_values_array_string, [:parameter_id, :timestamp],
                     name: "parameter_values_array_string_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_array_string, [:timestamp],
                     name: "parameter_values_array_string_timestamp_index"
                   )

    drop table(:parameter_values_array_string)

    drop constraint(:parameter_values_bool, "parameter_values_bool_parameter_id_fkey")

    drop_if_exists index(:parameter_values_bool, [:parameter_id, :timestamp],
                     name: "parameter_values_bool_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_bool, [:timestamp],
                     name: "parameter_values_bool_timestamp_index"
                   )

    drop table(:parameter_values_bool)

    drop constraint(:parameter_values_double, "parameter_values_double_parameter_id_fkey")

    drop_if_exists index(:parameter_values_double, [:parameter_id, :timestamp],
                     name: "parameter_values_double_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_double, [:timestamp],
                     name: "parameter_values_double_timestamp_index"
                   )

    drop table(:parameter_values_double)

    drop constraint(:parameter_values_int, "parameter_values_int_parameter_id_fkey")

    drop_if_exists index(:parameter_values_int, [:parameter_id, :timestamp],
                     name: "parameter_values_int_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_int, [:timestamp],
                     name: "parameter_values_int_timestamp_index"
                   )

    drop table(:parameter_values_int)

    drop constraint(:parameter_values_json, "parameter_values_json_parameter_id_fkey")

    drop_if_exists index(:parameter_values_json, [:parameter_id, :timestamp],
                     name: "parameter_values_json_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_json, [:timestamp],
                     name: "parameter_values_json_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_json, [:value],
                     name: "parameter_values_json_value_index"
                   )

    drop table(:parameter_values_json)

    drop constraint(:parameter_values_string, "parameter_values_string_parameter_id_fkey")

    drop_if_exists index(:parameter_values_string, [:parameter_id, :timestamp],
                     name: "parameter_values_string_parameter_id_timestamp_index"
                   )

    drop_if_exists index(:parameter_values_string, [:timestamp],
                     name: "parameter_values_string_timestamp_index"
                   )

    drop table(:parameter_values_string)

    drop table(:parameters)

    drop_if_exists unique_index(:sec_nodes, [:uuid], name: "sec_nodes_unique_uuid_index")

    drop_if_exists index(:sec_nodes, [:equipment_id], name: "equipment_id_index")

    drop table(:sec_nodes)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
