defmodule SecopService.Repo.Migrations.AddFavouriteAndStateToSecNodes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sec_nodes) do
      add :favourite, :boolean, null: false, default: false
      add :state, :text, null: false, default: "active"
    end
  end

  def down do
    alter table(:sec_nodes) do
      remove :state
      remove :favourite
    end
  end
end
