defmodule SecantService.Repo.Migrations.AddOphydClass do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sec_nodes) do
      add :ophyd_class, :text
    end
  end

  def down do
    alter table(:sec_nodes) do
      remove :ophyd_class
    end
  end
end
