defmodule :"Elixir.SecopService.Repo.Migrations.Storage-size" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sec_nodes) do
      add :datapoint_count, :bigint, null: false, default: 0
      add :disk_size_bytes, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:sec_nodes) do
      remove :disk_size_bytes
      remove :datapoint_count
    end
  end
end
